### PR TITLE
[README] Port colors guide from taskbar styler, add reveal guide

### PR DESCRIPTION
**Pull request by SandTechStuff**
I noticed there is no documentation on colors for the Start Menu Styling Guide, even though there is for the Taskbar Styling Guide. This PR adds the colors guide with minor tweaks to be more relevant for the Start Menu. This also adds a guide on the Reveal effect.

Submitting as a draft, as I very well could have made mistakes. Let me know what you think.

### CODE REVIEW

**Comment by bbmaster123** [comment]
thanks, appreciate the help! Been busier than usual the past few days, didn't even see this PR until just now, my apologies!

Looks good :)
Although I haven't double checked every target and style is correct. Also if you don't mind, I'd like to add a few quick things, like force light/dark mode, background image (which requires a url), semantic zoom, instructions for search, maybe a few others

btw, RevealBackgroundBrush does happen to work on some targets, (not sure why not all targets) but generally it looks awful except on very small targets. Its not diffuse enough, and has a fairly sharp circular cut off. I agree with not suggesting to use it though, or maybe not even mention it?

**Comment by SandTechStuff** [comment]
> didn't even see this PR until just now, my apologies!

No problem

> Also if you don't mind, I'd like to add a few quick things, like force light/dark mode, background image (which requires a url), semantic zoom, instructions for search, maybe a few others

Not sure what you mean by this. Do you want me to add these things, or are you saying you will? If you want to make changes, why not commit directly to the repo? But if you do want to add things, go for it.

> btw, RevealBackgroundBrush does happen to work on some targets, (not sure why not all targets) but generally it looks awful except on very small targets. Its not diffuse enough, and has a fairly sharp circular cut off. I agree with not suggesting to use it though, or maybe not even mention it?

Interesting, every time I have tried it didn't work. Another reason I choose to include it, besides the fact that I previously believed RevealBackgroundBrush was completely dysfunctional, was to prevent any confusion on why Reveal _Border_ Brush is to be used on things other than borders.

_I'll set this as ready to review._

**Comment by bbmaster123** [comment]
> or are you saying you will?

yea I'll add stuff :)

> why not commit directly to the repo?

yea I suppose I could, I didn't think of it haha

> prevent any confusion on why Reveal Border Brush is to be used on things other than borders.

Yea true, good point, we'll leave it in!

**Comment by bbmaster123** [comment]
ok looks good to me, merging now!
Thanks again Sand! :)

**Comment by m417z** [comment]
Looks great, thanks guys! I pushed [a follow-up commit](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/commit/e3e809686d3d6f9476689aa9019766f42d61a857) with minor typo/formatting fixes.

**Pull request merged**
