### PR TITLE
RosePine theme for start menu

### PR DESCRIPTION
**Pull request by lunar-os**
screenshot

### CODE REVIEW

**Comment by bbmaster123** [comment]
looks very nice, thanks for the submission :)
I'll test it later today when I have some time!

**Comment by lunar-os** [comment]
> looks very nice, thanks for the submission :)
> 
> I'll test it later today when I have some time!

Thanks lmk if u add it to the repo :)

**Comment by bbmaster123** [comment]
I'd like to add this to the repo, but I'm noticing a few small issues:

If you have the user shortcuts enabled at the bottom (downloads, documents, pics) they get squished up against the right side. Did you want to completely disable them, move them somewhere else, resize them, or something else?

The user tile is invisible but still functional. Intentional?

Also the expanded folder view is a bit cut off, maybe slide it over a bit?
target is StartMenu:ExpandedFolderList

**Comment by lunar-os** [comment]
> I'd like to add this to the repo, but I'm noticing a few small issues:
> 
> 
> 
> If you have the user shortcuts enabled at the bottom (downloads, documents, pics) they get squished up against the right side. Did you want to completely disable them, move them somewhere else, resize them, or something else?
> 
> 
> 
> The user tile is invisible but still functional. Intentional?
> 
> 
> 
> Also the expanded folder view is a bit cut off, maybe slide it over a bit?
> 
> target is StartMenu:ExpandedFolderList

Sorry I'm away from my computer but thanks for updating it. i'm new to how github works so do i have to do anything else for it to be added to the repository?

**Comment by bbmaster123** [comment]
Mainly I just want to know how you'd like to handle the user shortcuts buttons. as is right now, it looks good with up to 3 buttons, after which settings disappears and things start going behind other things.
If you just want to have the note at the top of the readme, then everything else is good and I'm ready to merge this with your go ahead :)

**Comment by bbmaster123** [comment]
I'm just going to go ahead with the note in the readme, we can always change it later if you'd like
cheers

**Pull request merged**
