### PR TITLE
fix `SideBySide2` & `SideBySide` compat with insider builds

### LINKED ISSUE #25: Recommended section is shifted in "SideBySide" theme
As the title says, the Recommended section is shifted to the left a little bit, causing the left half of the recommended pins to be cut off in the Start Menu. This happens in both the integrated theme and after manually installing it.

With less recommendations:
Screenshot 2024-06-10 183007

With defaults:
Screenshot 2024-06-10 184811

With more recommendations:
Screenshot 2024-06-10 184828

With recommendations but no recent files and apps:
Screenshot 2024-06-10 184920

If needed, I have included system information in case it is relevant for this issue:

AMD Ryzen 9 5900 12-Core Processor                3.00 GHz
Edition: Windows 11 Home 
Version: 23H2
OS build: 22631.3672
Windhawk mod: Windows 11 Start Menu Styler
Theme: SideBySide

### LINKED ISSUE #28: SidebySide2 Issue
Apps Drawer is not showing apps,  How can this be corrected? Using SideBySide2 theme. 

image

### PR DESCRIPTION
**Pull request by SunsetTechuila**
fixes #25

fixes #28

fixes ramensoftware/windhawk-mods#611

fixes ramensoftware/windhawk-mods#733

fixes ramensoftware/windhawk-mods#751

### CODE REVIEW

**Comment by m417z** [comment]
Thank you. The problem with adding support for 24H2/insider builds is that it breaks support for Win11 23H2 which is the most common version at this point. One solution is to have two themes, one for 23H2 and one for 24H2. Insider builds are less of a priority but we can have themes for dev builds as well if there's demand and somebody's willing to maintain them.

**Comment by SunsetTechuila** [comment]
> it breaks support for Win11 23H2

Hello, I don't have a chance to check right now, but I seriously doubt that my changes will have any impact on the current stable win11 builds

**Comment by m417z** [comment]
At least for https://github.com/ramensoftware/windows-11-start-menu-styling-guide/issues/28, as far as I understand, fixing it breaks 23H2 because the offsets in both versions are different. But maybe I'm wrong, so please test it.

@bbmaster123 worked on it recently so he might have some input.

**Comment by SunsetTechuila** [comment]
> the offsets in both versions are different.

No, the problem is in the menu width, as you can see by the code I added

**Comment by bbmaster123** [comment]
this is how your updated code looks on my 23h2:

image

While you did indeed fixed the recommended section on 23h2, some things are still a bit off. It _does_ look better on my 24h2. It fixes the menu width. on both 23h2 and 24h2.

The thing is, the start menu _is_ being changed again to accommodate the new "start experiences" sidebar thing. In 24h2, the flag for that feature will be enabled for most people, while most people on 23h2 wont have that enabled unless they force enable it. When enabled, the visual tree will be different, which messes up the positions/visibility of some elements. 

At least that's my current understanding of the situation, and I can see that enabling/disabling the feature flag does affect the styles being applied.

I spent a good chunk of time trying to make all elements fit well on 23h2:
image

I would think ideally, the best way forward would be like Michael suggested, which would be to have two versions that can either be picked manually, or chosen in the mod based upon your OS build. whichever way. 

That said, feel free to point out if I am wrong about anything. cheers!

**Comment by SunsetTechuila** [comment]
My changes have been tested on stable win11 and they don't break anything

#25 is fixed, but now there are some misalignments, which i can't reproduce on beta 
image
but it's still better than it was

ramensoftware/windhawk-mods#611 and ramensoftware/windhawk-mods#733 are connected and happen on stable channel as well. My changes fix these issues

**Comment by SunsetTechuila** [comment]
I made it draft because had plans to rework

**Pull request closed without merging**
