### PR TITLE
TranslucentStartMenu, change text color instead of background TintLuminosity

### PR DESCRIPTION
**Pull request by Undisputed00x**
Change text color to a bright gray #E1E1E1 instead of changing background Tint Luminosity,keeping a clear acrylic while text being visible on white background

### CODE REVIEW

**Comment by m417z** [comment]
It seems to me that the Tint Luminosity did a better job.

<details><summary>Tint Luminosity</summary>
<p>

image

</p>
</details> 

<details><summary>Gray text color</summary>
<p>

image</p>

</details>

**Comment by Undisputed00x** [comment]
@m417z i agree but it ruins the acrylic background 😐, this can be subjective and depends from person to person taste. Anyways you can reject the request and smo can adjust the background to his/her taste.

**Comment by m417z** [comment]
I understand, but from the amount of feedback about the unreadable text, I have a feeling that the average user will prefer that. How about we leave it as is for a while, release the new mod versions with that version, and see if there's any user feedback?

**Comment by Undisputed00x** [comment]
Yeah, of course.

**Pull request closed without merging**
